/***GET PASSWORD***/
SELECT PASSWORD FROM USER_VIEW WHERE LOGIN = ?
/***GET STATUS***/
SELECT USER_STATUS_VIEW.NAME FROM USER_STATUS_VIEW, USER_VIEW WHERE USER_VIEW.STATUS = USER_STATUS_VIEW.ID AND USER_VIEW.LOGIN = ?
/***LOGIN***/
INSERT INTO USER_STATUS (ID, VALUE, CHANGE_TIME) VALUES (?, 1, current_timestamp)
/***LOGOUT***/
INSERT INTO USER_STATUS (ID, VALUE, CHANGE_TIME) VALUES (?, 2, current_timestamp)
